# Generated by Django 4.2.4 on 2023-10-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo', models.CharField(max_length=100)),
                ('combustible', models.CharField(max_length=50)),
                ('carbono_litro', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
