# Generated by Django 4.2.4 on 2023-10-22 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vehiculo_delete_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='carbono_litro',
            new_name='carbono_por_litro',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='combustible',
            new_name='tipo_de_combustible',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='vehiculo',
            new_name='tipo_de_vehiculo',
        ),
    ]
