# Generated by Django 4.2.4 on 2023-11-22 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_jardin_carbono_jardin_c'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carbono',
        ),
    ]
