# Generated by Django 4.2.4 on 2023-11-27 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_carbono'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
