# Generated by Django 4.2.4 on 2023-11-27 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
