# Generated by Django 4.2.4 on 2023-10-11 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenStepApp', '0002_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
