# Generated by Django 4.2.4 on 2023-11-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenStepApp', '0005_encuesta_suma_puntaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='carbono_generado',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
