# Generated by Django 4.2.4 on 2023-11-15 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenStepApp', '0006_resultadoencuesta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultadoEncuesta',
        ),
    ]
