# Generated by Django 4.2.4 on 2023-11-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenStepApp', '0007_carbono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='carbono_generado',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
