# Generated by Django 4.2.4 on 2023-11-27 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenStepApp', '0007_delete_resultadoencuesta'),
        ('GreenStepApp', '0009_alter_encuesta_carbono_generado'),
    ]

    operations = [
    ]
